# generated by datamodel-codegen:
#   filename:  Person.json

from __future__ import annotations

from typing import Any, Optional

from pydantic import ConfigDict, Field, constr

from oold.model import LinkedBaseModel


class Thing(LinkedBaseModel):
    model_config = ConfigDict(
        json_schema_extra={"title": "Thing"},
    )
    type: Optional[str] = Field(
        "playground:Thing", json_schema_extra={"options": {"hidden": True}}
    )
    name: Optional[constr(min_length=1)] = "A Thing"
    """
    The things name
    """


class Person(Thing):
    model_config = ConfigDict(
        json_schema_extra={"title": "Person"},
    )
    type: Optional[Any] = Field(
        "playground:Person",
        json_schema_extra={
            "$comment": "Already defined in playground:Thing -> we override just the default"
        },
    )
    name: Optional[Any] = "John Doe"
    """
    First and Last name
    """
    age: Optional[int] = None
