# generated by datamodel-codegen:
#   filename:  Foo.json

from __future__ import annotations

from pydantic.v1 import Field

from oold.model.v1 import LinkedBaseModel


class Bar2(LinkedBaseModel):
    class Config:
        schema_extra = {"title": "Bar2"}

    id: str | None = None
    type: list[str] | None = ["Bar2"]
    prop1: str | None = None


class Bar(Bar2):
    class Config:
        schema_extra = {"title": "Bar"}

    type: list[str] | None = ["Bar"]
    prop2: str | None = None


class Foo(LinkedBaseModel):
    class Config:
        schema_extra = {"title": "Foo"}

    id: str
    type: list[str] | None = ["Foo"]
    literal: str | None = None
    b: Bar | None = Field(None, range="Bar.json", x_oold_required_iri=True)
    b_default: Bar | None = Field(
        default_factory=lambda: Bar.parse_obj("ex:b"), range="Bar.json"
    )
    b_set_later: Bar | None = Field(None, range="Bar.json")
    b2: list[Bar] | None = Field(None, range="Bar.json")
