# generated by datamodel-codegen:
#   filename:  Foo.json

from __future__ import annotations

from pydantic import ConfigDict, Field

from oold.model import LinkedBaseModel


class Bar2(LinkedBaseModel):
    model_config = ConfigDict(
        json_schema_extra={"title": "Bar2"},
    )
    id: str | None = None
    type: list[str] | None = ["Bar2"]
    prop1: str | None = None


class Bar(Bar2):
    model_config = ConfigDict(
        json_schema_extra={"title": "Bar"},
    )
    type: list[str] | None = ["Bar"]
    prop2: str | None = None


class Foo(LinkedBaseModel):
    model_config = ConfigDict(
        json_schema_extra={"title": "Foo"},
    )
    id: str
    type: list[str] | None = ["Foo"]
    literal: str | None = None
    b: Bar | None = Field(
        None, json_schema_extra={"range": "Bar.json", "x-oold-required-iri": True}
    )
    b_default: Bar | None = Field(
        default_factory=lambda: Bar.model_validate("ex:b"),
        json_schema_extra={"range": "Bar.json"},
    )
    b_set_later: Bar | None = Field(None, json_schema_extra={"range": "Bar.json"})
    b2: list[Bar] | None = Field(None, json_schema_extra={"range": "Bar.json"})
